### ISSUE TITLE
Bug Detail "Processando informações de estatisticas"

### ISSUE THREAD

**Issue by LucasRiibeiro** [cleitonme/izing.open.io#1]
Boa tarde tudo bem?, sabem me dizer como resolve este bug, fica aparecendo direto na tela, teve haver algo com Webhook?
![Bug Datail](https://github.com/cleitonme/izing.open.io/assets/147555373/8bee1a55-25de-4348-855e-d757b5bbf377)

**Comment by cleitonme** [comment]
teria ver log backend tambem

**Comment by LucasRiibeiro** [comment]
Certo, aqui esta log: 
{
  name: 'JsonWebTokenError',
  message: 'jwt must be provided',
  level: 'error',
  stack: 'JsonWebTokenError: jwt must be provided\n' +
    '    at module.exports (/home/deploy/izing1/backend/node_modules/jsonwebtoken/verify.js:60:17)\n' +
    '    at decode (/home/deploy/izing1/backend/src/libs/decodeTokenSocket.ts:34:27)\n' +
    '    at /home/deploy/izing1/backend/src/libs/socket.ts:35:39\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/deploy/izing1/backend/dist/libs/socket.js:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/home/deploy/izing1/backend/dist/libs/socket.js:4:12)\n' +
    '    at Array.<anonymous> (/home/deploy/izing1/backend/src/libs/socket.ts:32:33)\n' +
    '    at run (/home/deploy/izing1/backend/node_modules/socket.io/dist/namespace.js:66:19)\n' +
    '    at Namespace.run (/home/deploy/izing1/backend/node_modules/socket.io/dist/namespace.js:77:9)\n' +
    '    at Namespace._add (/home/deploy/izing1/backend/node_modules/socket.io/dist/namespace.js:110:14)\n' +
    '    at Client.doConnect (/home/deploy/izing1/backend/node_modules/socket.io/dist/client.js:98:28)\n' +
    '    at Client.connect (/home/deploy/izing1/backend/node_modules/socket.io/dist/client.js:69:25)\n' +
    '    at Client.ondecoded (/home/deploy/izing1/backend/node_modules/socket.io/dist/client.js:206:22)\n' +
    '    at Decoder.Emitter.emit (/home/deploy/izing1/backend/node_modules/component-emitter/index.js:145:20)\n' +
    '    at Decoder.add (/home/deploy/izing1/backend/node_modules/socket.io/node_modules/socket.io-parser/dist/index.js:120:23)\n' +
    '    at Client.ondata (/home/deploy/izing1/backend/node_modules/socket.io/dist/client.js:188:26)\n' +
    '    at Socket.emit (node:events:519:28)\n' +
    '    at Socket.emit (node:domain:488:12)\n' +
    '    at Socket.onPacket (/home/deploy/izing1/backend/node_modules/engine.io/lib/socket.js:121:16)\n' +
    '    at WebSocket.emit (node:events:519:28)\n' +
    '    at WebSocket.emit (node:domain:488:12)\n' +
    '    at WebSocket.onPacket (/home/deploy/izing1/backend/node_modules/engine.io/lib/transport.js:86:10)\n' +
    '    at WebSocket.onData (/home/deploy/izing1/backend/node_modules/engine.io/lib/transport.js:96:10)\n' +
    '    at WebSocket.onData (/home/deploy/izing1/backend/node_modules/engine.io/lib/transports/websocket.js:59:11)\n' +
    '    at WebSocket.emit (node:events:519:28)\n' +
    '    at WebSocket.emit (node:domain:488:12)\n' +
    '    at Receiver.receiverOnMessage (/home/deploy/izing1/backend/node_modules/engine.io/node_modules/ws/lib/websocket.js:834:20)\n' +
    '    at Receiver.emit (node:events:519:28)\n' +
    '    at Receiver.emit (node:domain:488:12)\n' +
    '    at Receiver.dataMessage (/home/deploy/izing1/backend/node_modules/engine.io/node_modules/ws/lib/receiver.js:437:14)\n' +
    '    at Receiver.getData (/home/deploy/izing1/backend/node_modules/engine.io/node_modules/ws/lib/receiver.js:367:17)\n' +
    '    at Receiver.startLoop (/home/deploy/izing1/backend/node_modules/engine.io/node_modules/ws/lib/receiver.js:143:22)\n' +
    '    at Receiver._write (/home/deploy/izing1/backend/node_modules/engine.io/node_modules/ws/lib/receiver.js:78:10)',
  timestamp: '2024-06-05T02:34:36.853Z'
}

**Comment by cleitonme** [comment]
faça instalação nova limpa... para verificar se problema persiste... lembrando essa versão recomendado node 20, tem no material vídeos e texto ensinando instalar

**Comment by LucasRiibeiro** [comment]
Beleza, valeu, a versão do node que estou utilizando é a 20.14.0

**Comment by LucasRiibeiro** [comment]
O estranho que depois de um tempo para de dar este mensagem e funciona normalmente, e depois volta, mas vou fazer a reinstalação aqui e vou verificar se persiste. Obrigado

**Comment by cleitonme** [comment]
pode ser servidor nao ta dando conta erro 'JsonWebTokenError e outra coisa ele da tela login

**Comment by LucasRiibeiro** [comment]
Entendi, é pode ser mesmo, porque quando faço o teste de madrugada quando não tem ninguém conectado ele não da este erro, mas vou ficar olhando no log lá se eu achar algo eu mando aqui, Obrigado pela ajuda meu irmão

**Comment by cleitonme** [comment]
qts whatsapp? qts? usuarios? qual configuracao vps?

**Comment by Elton-Coelho** [comment]
O meu aparecia esse erro!
Quando a pagina fica muito tempo aberta,
ao atualizar a página parava de aparece o erro.
Parece que era memoria cache.
Antes o sistema usava 800mb a 1,5gb de RAM.

Ao realizar uma nova instalação, não apareceu mais o erro.
Agora está com uso na casa de 3gb de RAM.
